version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5002
      API_KEY_ENCHAGE_RATES: "a2lPdXXru7MON55V868qzNJqQOSNXLJO"
      SECRET: "!@#%@#gf^&bdsSsfSp!@F^R&sdf"
    ports:
      - 5002:5002
    networks:
      - fetch-network

networks:
  fetch-network: